### ISSUE TITLE
Git flow branching model

### ISSUE THREAD

**Issue by LongYC** [bemyeyes/bemyeyes-android#1]
This project seems pretty new with only a master branch, I would like to propose using the [gitflow](http://nvie.com/posts/a-successful-git-branching-model/ "A successful Git branching model") branching model for collaboration.

**Comment by jchillerup** [comment]
It's a good idea. I've used it previously for other projects, and I think it makes sense as soon as there is more than one developer working. Let's do that from this point. Thanks!

**Comment by LongYC** [comment]
Will need your help to create the `develop` branch out from current `master` branch and perhaps remove the `master` branch for now until the project has a release. Hopefully this project will attract more contributors soon, would love to see Be My Eyes on Android!

**Comment by jchillerup** [comment]
Yes, that's right. I just ran git flow init, so now the develop branch is the main branch for development. I'll get the time to sit down and write some code for BME next week probably (doing this voluntarily). If you want to work on the project I think we should take a Skype meeting and discuss how to get you what you need in order to get started. Best, JC
